spring:
  application:
    name: receiver
  rabbitmq:
    virtual-host: /
app:
  async:
    app:
      createTopology: true
      listenReplies: false
      maxRetries: 3
      withDLQRetry: true
      queueType: quorum

