spring:
  application:
    name: sender
  rabbitmq:
    username: other
    virtual-host: /
server:
  port: 4001
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus
app:
  async:
    createTopology: false
    listenReplies: false
